version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: '13:00'
  open-pull-requests-limit: 10
  target-branch: development
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: '13:00'
  open-pull-requests-limit: 10
  target-branch: development
