version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
    time: '08:00'
  open-pull-requests-limit: 10
  target-branch: "development"
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
    time: '08:00'
  open-pull-requests-limit: 10
  target-branch: "development"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
    time: '08:00'
  open-pull-requests-limit: 10
  target-branch: "development"
