# This enables spell checking using the built-in US English dictionary

extends: spelling
message: "Did you really mean '%s'?"
ignorecase: true
level: error
ignore: .github/vale-styles/Semmle/ignore.txt
