backend:
  name: git-gateway
  repo: ManticoreGamesInc/platform-documentation
  branch: netlifycms

media_folder: src/img/
public_folder: /img/
publish_mode: editorial_workflow
site_url: https://dev.manticoreplatform.com/docs/
logo_url: https://i.imgur.com/iqNiYlm.png

collections:
  - name: news
    label: news
    folder: src/news
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: events
    label: events
    folder: src/events
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
